# Generated by Django 4.2.1 on 2023-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hexagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Enter the number of the hexagram, eg. Hexagram 3', max_length=80, verbose_name='Number')),
                ('description', models.CharField(help_text='Enter ', max_length=100, verbose_name='Description')),
                ('meaning', models.CharField(max_length=200, verbose_name='meaning')),
            ],
        ),
    ]
